# Generated by Django 5.2 on 2025-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_playlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('generation_prompt_keywords', models.TextField(help_text="Keywords or base prompt for OpenAI to generate tracks, e.g., 'upbeat electronic for coding'")),
                ('target_song_count', models.PositiveIntegerField(default=10)),
                ('cached_tracks', models.JSONField(blank=True, help_text='JSON containing the list of tracks: [{title, artist, duration}] for the current day', null=True)),
                ('last_refreshed_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
