# Generated by Django 4.2.20 on 2025-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_specializedplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodmodel',
            name='category',
            field=models.CharField(blank=True, default='Neutral', max_length=50),
        ),
    ]
