# Generated by Django 4.2.20 on 2025-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_moodmodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order_in_playlist']},
        ),
        migrations.AddField(
            model_name='track',
            name='order_in_playlist',
            field=models.IntegerField(default=0),
        ),
    ]
