# Generated by Django 4.2.20 on 2025-05-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_track_options_track_order_in_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
