# Generated by Django 4.2.21 on 2025-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
