# Generated by Django 4.2.20 on 2025-05-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_track_spotify_uri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
