# Generated by Django 4.2.21 on 2025-05-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='had_llm_fallbacks',
            field=models.BooleanField(default=False),
        ),
    ]
