# Generated by Django 4.2.21 on 2025-05-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_playlist_had_llm_fallbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='had_llm_fallbacks',
        ),
        migrations.AddField(
            model_name='playlist',
            name='llm_fallback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='total_tracks_generated',
            field=models.IntegerField(default=0),
        ),
    ]
