services:
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  frontend:
    build:
      context: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SPOTIFY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
      VITE_SPOTIFY_CLIENT_SECRET: ${VITE_SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./backend/certs:/app/certs:ro

  backend:
    build:
      context: ./backend
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./backend:/app
      - ./backend/certs:/app/certs:ro
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-https://localhost:3000}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL:-https://localhost:3000}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SPOTIPY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${VITE_SPOTIFY_CLIENT_SECRET}
      SSL_CERTIFICATE: /app/certs/cert.pem
      SSL_PRIVATE_KEY: /app/certs/key.pem
    depends_on:
      - db

volumes:
  postgres_data:
